[package]
rust-version.workspace = true
name = "sdkwork-drama-episode-repository-sqlx"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true


[lints]
workspace = true
[dependencies]
sdkwork-drama-episode-service = { workspace = true }
async-trait = { workspace = true }
sqlx = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
